### Application
app:
  TNA_ADMIN_LOGIN: ${TNA_ADMIN_LOGIN}
  TNA_ADMIN_PASSWORD: ${TNA_ADMIN_PASSWORD}

#### Server
server:
  port: 8080
  servlet:
    context-path: /api

errors:
  expose-arguments: ALWAYS

### Spring Data
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
