### Integration Test
app:
    tna-admin-login: admin
    tna-admin-password: admin

spring:
    datasource:
        driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
        url: jdbc:tc:postgresql:///integration
    liquibase:
        drop-first: true
    test:
        database:
            replace: none
